### PR TITLE
feat: add releases and detail pages, fix some design issues 

### LINKED ISSUE #21: feat: changelog and release pages
release.gnome.org

### PR DESCRIPTION
**Pull request by 3nln**
Closes #21

### CODE REVIEW

**Comment by 3nln** [comment]
image

File: data/releases.js [hunk 1]
```diff
@@ -0,0 +1,28 @@
...
+    date: "Aprel/May 2025",
+    href: "/releases/25.05",
+    featured: true,
+  },
+  {
+    version: "25.11",
+    codename: "Jadid",
+    date: "Noyabr 2025",
+    href: "/releases/25.11",
+  },
```
Comment (bahrom04) [inline data/releases.js]:
```suggestion
  {
    version: "25.11",
    codename: "Jadid",
    date: "Noyabr 2025",
    href: "/releases/25.11",
    featured: true,
  },
```

**Review by bahrom04 — CHANGES_REQUESTED** [review]

**Comment by 3nln** [comment]
@bahrom04 done

**Comment by 3nln** [comment]
> @3nln 26.05 versiyasini featured qilish kerak edi tepaga chiqarib qoʻyib

@bahrom04 fixed

**Comment by bahrom04** [comment]
Ishlati rahmat
